use gpui::{AssetSource, Result, SharedString};
use std::borrow::Cow;

// `icon_bytes()`/`ICON_ASSETS` and `file_icon_bytes()`/`FILE_ICON_ASSETS`,
// generated by `build.rs` from `assets/icons/*.svg` and
// `assets/icons/file_icons/*.svg`.
include!(concat!(env!("OUT_DIR"), "/icons_assets.rs"));

pub struct GitCometAssets;

impl GitCometAssets {
    fn load_static(path: &str) -> Option<Cow<'static, [u8]>> {
        match path {
            "gitcomet-window-icon.png" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet-window-icon.png"
            ))),
            "gitcomet-512.png" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet-512.png"
            ))),
            "gitcomet_logo.svg" => Some(Cow::Borrowed(include_bytes!(
                "../../../assets/gitcomet_logo.svg"
            ))),
            other => icon_bytes(other)
                .or_else(|| file_icon_bytes(other))
                .map(Cow::Borrowed),
        }
    }

    fn list_static(dir: &str) -> Vec<SharedString> {
        match dir.trim_end_matches('/') {
            // GPUI's AssetRegistry registers only list(""); it does not recurse
            // into directory entries. Include every embedded file here.
            "" => [
                "gitcomet-window-icon.png",
                "gitcomet-512.png",
                "gitcomet_logo.svg",
            ]
            .into_iter()
            .chain(ICON_ASSETS.iter().copied())
            .chain(FILE_ICON_ASSETS.iter().copied())
            .map(SharedString::from)
            .collect(),
            "icons" => ICON_ASSETS
                .iter()
                .map(|path| SharedString::from(*path))
                .chain(std::iter::once("icons/file_icons".into()))
                .collect(),
            "icons/file_icons" => FILE_ICON_ASSETS
                .iter()
                .map(|path| SharedString::from(*path))
                .collect(),
            _ => vec![],
        }
    }
}

impl AssetSource for GitCometAssets {
    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {
        Ok(Self::load_static(path))
    }

    fn list(&self, path: &str) -> Result<Vec<SharedString>> {
        Ok(Self::list_static(path))
    }
}

#[cfg(test)]
mod tests {
    use super::{FILE_ICON_ASSETS, GitCometAssets, ICON_ASSETS};
    use gpui::{AssetRegistry, AssetSource, DevicePixels, SvgRenderer, SvgSize, size};
    use std::{collections::BTreeSet, path::Path, sync::Arc};

    fn expected_asset_paths() -> impl Iterator<Item = &'static str> {
        [
            "gitcomet-window-icon.png",
            "gitcomet-512.png",
            "gitcomet_logo.svg",
        ]
        .into_iter()
        .chain(ICON_ASSETS.iter().copied())
        .chain(FILE_ICON_ASSETS.iter().copied())
    }

    #[test]
    fn root_listing_contains_every_asset_once() {
        let listed = GitCometAssets.list("").expect("list root assets");
        let paths: BTreeSet<&str> = listed.iter().map(|path| path.as_ref()).collect();

        assert_eq!(paths.len(), listed.len(), "duplicate root asset paths");
        assert_eq!(
            paths,
            expected_asset_paths().collect(),
            "root listing must contain every file without directory placeholders"
        );
    }

    #[test]
    fn gpui_registry_preserves_every_asset() {
        // Exercise the same conversion as Application::with_assets. Checking
        // GitCometAssets::load alone misses paths omitted from the root listing.
        let registry = AssetRegistry::from(GitCometAssets);
        for path in expected_asset_paths() {
            let expected = GitCometAssets
                .load(path)
                .expect("load embedded asset")
                .unwrap_or_else(|| panic!("missing embedded asset: {path}"));
            let actual = registry
                .load(path)
                .unwrap_or_else(|| panic!("GPUI registry cannot load {path}"));
            assert!(!actual.is_empty(), "empty asset: {path}");
            assert_eq!(actual, expected, "GPUI changed asset bytes: {path}");
        }
        for path in ["icons", "icons/file_icons", "icons/does-not-exist.svg"] {
            assert!(registry.load(path).is_none(), "unexpected asset: {path}");
        }
    }

    #[test]
    fn registered_svgs_render_visible_pixels() {
        let registry = Arc::new(AssetRegistry::from(GitCometAssets));
        let renderer = SvgRenderer::new(Arc::clone(&registry));
        for path in expected_asset_paths().filter(|path| path.ends_with(".svg")) {
            let bytes = registry
                .load(path)
                .unwrap_or_else(|| panic!("GPUI registry cannot load {path}"));
            let parsed = renderer
                .parse_svg(&bytes)
                .unwrap_or_else(|err| panic!("cannot parse {path}: {err}"));
            for edge in [16, 32] {
                let dimensions = size(DevicePixels(edge), DevicePixels(edge));
                let image = renderer
                    .render_parsed(&parsed, SvgSize::ExactSize(dimensions))
                    .unwrap_or_else(|err| panic!("cannot render {path} at {edge}px: {err}"));
                assert_eq!(image.size(0), dimensions, "incorrect size: {path}");
                let pixels = image.as_bytes(0).expect("rendered SVG frame");
                assert!(
                    pixels.chunks_exact(4).any(|pixel| pixel[3] != 0),
                    "{path} renders blank at {edge}px"
                );
            }
        }
    }

    #[test]
    fn icon_assets_directory_matches_registry() {
        let icons_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/icons");
        let on_disk: BTreeSet<String> = std::fs::read_dir(&icons_dir)
            .expect("expected icons asset directory")
            .map(|entry| {
                let entry = entry.expect("expected icon asset entry");
                let name = entry.file_name();
                format!("icons/{}", name.to_string_lossy())
            })
            .collect();

        let registered: BTreeSet<String> = GitCometAssets::list_static("icons")
            .into_iter()
            .map(|path| path.to_string())
            .collect();

        assert_eq!(
            registered, on_disk,
            "expected the asset registry to cover every icons/* entry"
        );

        for icon in &registered {
            if icon == "icons/file_icons" {
                continue;
            }
            assert!(
                GitCometAssets::load_static(icon).is_some(),
                "expected {icon} to be loadable from the asset registry"
            );
        }

        let file_icons_dir = icons_dir.join("file_icons");
        let file_icons_on_disk: BTreeSet<String> = std::fs::read_dir(&file_icons_dir)
            .expect("expected file_icons asset directory")
            .map(|entry| {
                let name = entry.expect("expected file icon entry").file_name();
                format!("icons/file_icons/{}", name.to_string_lossy())
            })
            .collect();
        let file_icons_registered: BTreeSet<String> =
            GitCometAssets::list_static("icons/file_icons")
                .into_iter()
                .map(|path| path.to_string())
                .collect();

        assert_eq!(
            file_icons_registered, file_icons_on_disk,
            "expected the registry to cover every icons/file_icons/*.svg file"
        );

        for icon in &file_icons_registered {
            assert!(
                GitCometAssets::load_static(icon).is_some(),
                "expected {icon} to be loadable from the asset registry"
            );
        }
    }
}
