pub(crate) mod common;

mod branch_sidebar;
mod branch_sidebar_cache;
mod sidebar_sticky;
pub(crate) use sidebar_sticky::bench_sidebar_sticky;
mod branch_sidebar_extreme_scale;
mod clipboard;
mod commit_details;
mod conflict_load_duplication;
mod conflict_resolved_output_gutter_scroll;
mod conflict_resolved_output_live_syntax;
mod conflict_search_query_update;
mod conflict_split_resize_step;
mod conflict_streamed_provider;
mod conflict_streamed_resolved_output;
mod conflict_three_way_prepared_syntax_scroll;
mod conflict_three_way_scroll;
mod conflict_three_way_visible_map_build;
mod conflict_two_way_diff_build;
mod conflict_two_way_split_scroll;
mod conflict_two_way_word_highlights;
mod diff_open_conflict_compare_first_window;
mod diff_open_file_inline_first_window;
mod diff_open_file_split_first_window;
mod diff_open_image_preview_first_paint;
mod diff_open_markdown_preview_first_window;
mod diff_open_patch_100k_lines_first_window;
mod diff_open_patch_deep_window;
mod diff_open_patch_first_window;
mod diff_open_svg_dual_path_first_window;
mod diff_refresh_rev_only_same_content;
mod diff_split_resize_drag_step;
mod display;
mod file_diff_inline_syntax_projection;
mod file_diff_replacement_alignment;
mod file_diff_syntax_cache_drop;
mod file_diff_syntax_pair_lookup;
mod file_diff_syntax_prepare;
mod file_diff_syntax_query_stress;
mod file_diff_syntax_reparse;
mod frame_timing;
mod fs_event;
mod git_ops;
mod history_cache_build;
mod history_cache_build_extreme_scale;
mod history_column_resize_drag_step;
mod history_graph;
mod history_load_more_append;
mod history_scope_switch;
mod indexed_history;
mod keyboard;
mod large_file_diff_scroll;
mod large_html_syntax;
mod markdown_preview_parse_build;
mod markdown_preview_render;
mod markdown_preview_scroll;
mod merge_open_bootstrap;
mod network;
mod open_repo;
mod pane_resize_drag_step;
mod patch_diff_paged_rows;
mod patch_diff_search_query_update;
mod picker_prompt;
mod prepared_syntax_chunk_miss_cost;
mod prepared_syntax_multidoc_cache_hit_rate;
mod real_repo;
mod repo_switch;
mod repo_tab_drag;
mod resolved_output_recompute_incremental;
mod scrollbar_drag_step;
mod search;
mod staging;
mod status_list;
mod status_multi_select;
mod status_select_diff_open;
mod status_truncation;
mod text_input_long_line_cap;
mod text_input_prepaint_windowed;
mod text_input_runs_streamed_highlight;
mod text_input_wrap_incremental_burst_edits;
mod text_input_wrap_incremental_tabs;
mod text_model_bulk_load_large;
mod text_model_fragmented_edits;
mod text_model_snapshot_clone_cost;
mod undo_redo;
mod window_resize_layout;
mod window_resize_layout_extreme_scale;
mod worktree_preview_render;

pub(crate) use branch_sidebar::bench_branch_sidebar;
pub(crate) use branch_sidebar_cache::bench_branch_sidebar_cache;
pub(crate) use branch_sidebar_extreme_scale::bench_branch_sidebar_extreme_scale;
pub(crate) use clipboard::bench_clipboard;
pub(crate) use commit_details::bench_commit_details;
pub(crate) use common::{benchmark_criterion, benchmark_selectors_match_filter};
pub(crate) use conflict_load_duplication::bench_conflict_load_duplication;
pub(crate) use conflict_resolved_output_gutter_scroll::bench_conflict_resolved_output_gutter_scroll;
pub(crate) use conflict_resolved_output_live_syntax::bench_conflict_resolved_output_live_syntax;
pub(crate) use conflict_search_query_update::bench_conflict_search_query_update;
pub(crate) use conflict_split_resize_step::bench_conflict_split_resize_step;
pub(crate) use conflict_streamed_provider::bench_conflict_streamed_provider;
pub(crate) use conflict_streamed_resolved_output::bench_conflict_streamed_resolved_output;
pub(crate) use conflict_three_way_prepared_syntax_scroll::bench_conflict_three_way_prepared_syntax_scroll;
pub(crate) use conflict_three_way_scroll::bench_conflict_three_way_scroll;
pub(crate) use conflict_three_way_visible_map_build::bench_conflict_three_way_visible_map_build;
pub(crate) use conflict_two_way_diff_build::bench_conflict_two_way_diff_build;
pub(crate) use conflict_two_way_split_scroll::bench_conflict_two_way_split_scroll;
pub(crate) use conflict_two_way_word_highlights::bench_conflict_two_way_word_highlights;
pub(crate) use diff_open_conflict_compare_first_window::bench_diff_open_conflict_compare_first_window;
pub(crate) use diff_open_file_inline_first_window::bench_diff_open_file_inline_first_window;
pub(crate) use diff_open_file_split_first_window::bench_diff_open_file_split_first_window;
pub(crate) use diff_open_image_preview_first_paint::bench_diff_open_image_preview_first_paint;
pub(crate) use diff_open_markdown_preview_first_window::bench_diff_open_markdown_preview_first_window;
pub(crate) use diff_open_patch_100k_lines_first_window::bench_diff_open_patch_100k_lines_first_window;
pub(crate) use diff_open_patch_deep_window::bench_diff_open_patch_deep_window;
pub(crate) use diff_open_patch_first_window::bench_diff_open_patch_first_window;
pub(crate) use diff_open_svg_dual_path_first_window::bench_diff_open_svg_dual_path_first_window;
pub(crate) use diff_refresh_rev_only_same_content::bench_diff_refresh_rev_only_same_content;
pub(crate) use diff_split_resize_drag_step::bench_diff_split_resize_drag_step;
pub(crate) use display::bench_display;
pub(crate) use file_diff_inline_syntax_projection::bench_file_diff_inline_syntax_projection;
pub(crate) use file_diff_replacement_alignment::bench_file_diff_replacement_alignment;
pub(crate) use file_diff_syntax_cache_drop::bench_file_diff_syntax_cache_drop;
pub(crate) use file_diff_syntax_pair_lookup::bench_file_diff_syntax_pair_lookup;
pub(crate) use file_diff_syntax_prepare::bench_file_diff_syntax_prepare;
pub(crate) use file_diff_syntax_query_stress::bench_file_diff_syntax_query_stress;
pub(crate) use file_diff_syntax_reparse::bench_file_diff_syntax_reparse;
pub(crate) use frame_timing::bench_frame_timing;
pub(crate) use fs_event::bench_fs_event;
pub(crate) use git_ops::bench_git_ops;
pub(crate) use history_cache_build::bench_history_cache_build;
pub(crate) use history_cache_build_extreme_scale::bench_history_cache_build_extreme_scale;
pub(crate) use history_column_resize_drag_step::bench_history_column_resize_drag_step;
pub(crate) use history_graph::bench_history_graph;
pub(crate) use history_load_more_append::bench_history_load_more_append;
pub(crate) use history_scope_switch::bench_history_scope_switch;
pub(crate) use indexed_history::bench_indexed_history;
pub(crate) use keyboard::bench_keyboard;
pub(crate) use large_file_diff_scroll::bench_large_file_diff_scroll;
pub(crate) use large_html_syntax::bench_large_html_syntax;
pub(crate) use markdown_preview_parse_build::bench_markdown_preview_parse_build;
pub(crate) use markdown_preview_render::bench_markdown_preview_render;
pub(crate) use markdown_preview_scroll::bench_markdown_preview_scroll;
pub(crate) use merge_open_bootstrap::bench_merge_open_bootstrap;
pub(crate) use network::bench_network;
pub(crate) use open_repo::bench_open_repo;
pub(crate) use pane_resize_drag_step::bench_pane_resize_drag_step;
pub(crate) use patch_diff_paged_rows::bench_patch_diff_paged_rows;
pub(crate) use patch_diff_search_query_update::bench_patch_diff_search_query_update;
pub(crate) use picker_prompt::bench_picker_prompt;
pub(crate) use prepared_syntax_chunk_miss_cost::bench_prepared_syntax_chunk_miss_cost;
pub(crate) use prepared_syntax_multidoc_cache_hit_rate::bench_prepared_syntax_multidoc_cache_hit_rate;
pub(crate) use real_repo::bench_real_repo;
pub(crate) use repo_switch::bench_repo_switch;
pub(crate) use repo_tab_drag::bench_repo_tab_drag;
pub(crate) use resolved_output_recompute_incremental::bench_resolved_output_recompute_incremental;
pub(crate) use scrollbar_drag_step::bench_scrollbar_drag_step;
pub(crate) use search::bench_search;
pub(crate) use staging::bench_staging;
pub(crate) use status_list::bench_status_list;
pub(crate) use status_multi_select::bench_status_multi_select;
pub(crate) use status_select_diff_open::bench_status_select_diff_open;
pub(crate) use status_truncation::bench_status_truncation;
pub(crate) use text_input_long_line_cap::bench_text_input_long_line_cap;
pub(crate) use text_input_prepaint_windowed::bench_text_input_prepaint_windowed;
pub(crate) use text_input_runs_streamed_highlight::bench_text_input_runs_streamed_highlight;
pub(crate) use text_input_wrap_incremental_burst_edits::bench_text_input_wrap_incremental_burst_edits;
pub(crate) use text_input_wrap_incremental_tabs::bench_text_input_wrap_incremental_tabs;
pub(crate) use text_model_bulk_load_large::bench_text_model_bulk_load_large;
pub(crate) use text_model_fragmented_edits::bench_text_model_fragmented_edits;
pub(crate) use text_model_snapshot_clone_cost::bench_text_model_snapshot_clone_cost;
pub(crate) use undo_redo::bench_undo_redo;
pub(crate) use window_resize_layout::bench_window_resize_layout;
pub(crate) use window_resize_layout_extreme_scale::bench_window_resize_layout_extreme_scale;
pub(crate) use worktree_preview_render::bench_worktree_preview_render;
