//! Whether a path counts as a "generated file" the way GitHub does: hidden by
//! default in a pull request's Files list, and left out of reviewer-agent
//! material (docs/pr-mode.md) unless the scope is exactly that file.
//!
//! Matches GitHub's `linguist-generated` attribute:
//! <https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github>
//!
//! This module holds only the pure classification rule. Reading
//! `.gitattributes` at a commit is gix's job (`gitcomet-git-gix`), off the UI
//! thread; this is what it hands the answer to.

use std::path::Path;

/// Lockfiles GitHub Linguist treats as generated by default.
const BUILTIN_GENERATED_NAMES: &[&str] = &[
    "Cargo.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Gemfile.lock",
    "composer.lock",
    "go.sum",
];

/// Minified-file suffixes GitHub Linguist treats as generated by default.
const BUILTIN_GENERATED_SUFFIXES: &[&str] = &[".min.js", ".min.css"];

/// Whether `path` is on the built-in generated-file list: a short list modeled
/// on GitHub Linguist's own defaults (lockfiles and minified output), used
/// when `.gitattributes` says nothing about the path either way.
pub fn matches_builtin_generated_list(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    BUILTIN_GENERATED_NAMES.contains(&name)
        || BUILTIN_GENERATED_SUFFIXES
            .iter()
            .any(|suffix| name.ends_with(suffix))
}

/// Whether `path` counts as generated: `linguist_generated_attr` is the
/// resolved `linguist-generated` attribute for `path` at the commit in
/// question (`Some(true)` for `linguist-generated`/`linguist-generated=true`,
/// `Some(false)` for `-linguist-generated`/`linguist-generated=false`, `None`
/// when `.gitattributes` says nothing about the path, including when it isn't
/// mentioned at all). An explicit attribute always wins, even for a path the
/// built-in list would otherwise match — that's how `-linguist-generated`
/// un-marks a built-in one.
pub fn is_generated_file(path: &Path, linguist_generated_attr: Option<bool>) -> bool {
    linguist_generated_attr.unwrap_or_else(|| matches_builtin_generated_list(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_list_matches_known_lockfiles_and_minified_suffixes() {
        for name in [
            "Cargo.lock",
            "package-lock.json",
            "yarn.lock",
            "pnpm-lock.yaml",
            "poetry.lock",
            "Gemfile.lock",
            "composer.lock",
            "go.sum",
        ] {
            assert!(
                matches_builtin_generated_list(Path::new(name)),
                "{name} should be a built-in generated file"
            );
            assert!(
                matches_builtin_generated_list(Path::new(&format!("nested/dir/{name}"))),
                "{name} should match regardless of its directory"
            );
        }
        for name in ["app.min.js", "vendor/theme.min.css"] {
            assert!(
                matches_builtin_generated_list(Path::new(name)),
                "{name} should be a built-in generated file"
            );
        }
    }

    #[test]
    fn builtin_list_does_not_match_unrelated_files() {
        for name in ["Cargo.toml", "package.json", "main.rs", "min.js", "lock"] {
            assert!(
                !matches_builtin_generated_list(Path::new(name)),
                "{name} should not be a built-in generated file"
            );
        }
    }

    #[test]
    fn attribute_wins_over_the_builtin_list_in_either_direction() {
        // `-linguist-generated` un-marks a built-in lockfile.
        assert!(!is_generated_file(
            Path::new("Cargo.lock"),
            Some(false)
        ));
        // `linguist-generated` marks an otherwise-ordinary file.
        assert!(is_generated_file(
            Path::new("src/main.rs"),
            Some(true)
        ));
    }

    #[test]
    fn no_attribute_falls_back_to_the_builtin_list() {
        assert!(is_generated_file(Path::new("Cargo.lock"), None));
        assert!(!is_generated_file(Path::new("src/main.rs"), None));
    }
}
