[package]
name = "gitcomet-state"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
benchmarks = []
test-support = []

[dependencies]
gitcomet-core = { workspace = true }
notify = { workspace = true }
rustfs-mimalloc = { workspace = true }
smol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rustc-hash = { workspace = true }
strum = { workspace = true }
smallvec = { workspace = true }
tempfile = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
gitcomet-core = { workspace = true, features = ["test-support"] }
gitcomet-git-gix = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
gitcomet-fs-watch = { path = "../gitcomet-fs-watch" }

[target.'cfg(any(target_os = "macos", windows))'.dev-dependencies]
gitcomet-fs-watch = { path = "../gitcomet-fs-watch", features = ["test-support"] }
